# Generated by Django 4.2 on 2023-04-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=100)),
                ('weapon', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=15)),
                ('limited', models.BooleanField()),
                ('chromas', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
